package uz.dataFin.notificationbot.utils;

public enum BotState {
    SEND_PHONE,
    GET_CONTACT,
    SEND_MARKET_NAME_TEXT,
    GET_BALANCE,
    GET_START_DATE,
    REPORTS,
    SEND_BY_MONTH,
    SAVE_START_DATE,
    EDIT_START_DATE,
    EDIT_END_DATE,
    SEND_EXCEPTION,
    GET_START_DATEV2,
    TAKE_BALANCE,
    GET_PRODUCT,
    GET_NAME,
    SAVE_NAME,
    SEND_BTN_TYPE_FILE, EDIT2PDF, EDIT2JPG, EDIT2XLSX, SEND_BY_DAY, SEND_BY_WEEK, SEND_BY_LAST_MONTH, SEND_BY_SEASON, SEND_BY_YEAR, SEND_CALENDAR, SEND_BTN_SETTING, SEND_BTN_CHANGE_LANG, EDIT2UZ, EDIT2RU, EDIT2KRIL, SEND_BTN_MAIN_MANU, SEND_CONTINUE, SEND_AGREED_MONEY, SEND_REJECTED_MONEY, NEUTRAL

}
