package uz.dataFin.notificationbot.utils;

public enum BotState {
    SEND_PHONE,
    GET_CONTACT,
    SEND_MARKET_NAME_TEXT,
    GET_BALANCE,
    GET_START_DATE,
    REPORTS,
    SEND_BY_MONTH,
    SAVE_START_DATE,
    EDIT_START_DATE,
    EDIT_END_DATE,
    SEND_EXCEPTION,
    GET_START_DATEV2,
    TAKE_BALANCE,
    GET_PRODUCT,
    GET_NAME,
    SAVE_NAME,
    DEFAULT,
    SEND_BTN_TYPE_FILE, EDIT2PDF, EDIT2JPG, EDIT2XLSX, SEND_BY_DAY, SEND_BY_WEEK, SEND_BY_LAST_MONTH, SEND_BY_SEASON, SEND_BY_YEAR, SEND_CALENDAR, SEND_BTN_SETTING, SEND_BTN_CHANGE_LANG, EDIT2UZ, EDIT2RU, EDIT2KRIL, SEND_BTN_MAIN_MANU, SEND_CONTINUE, SEND_AGREED_MONEY, SEND_REJECTED_MONEY, GET_START_DATE_WAREHOUSE, SAVE_WAREHOUSE, GET_BY_PRODUCT_GROUP, GET_PRODUCT_GROUP_IN_API, SEND_WAREHOUSE_BACK, GET_REPORT_WAREHOUSE, GET_BY_PRODUCT, GET_PRODUCT_IN_API, GET_REPORT_WAREHOUSE_BY_PRODUCT, GET_START_DATE_TRADE, GET_START_DATE_CASH_BOX, GET_PERIOD, GET_ACCOUNT_DEBT, NEXT, NO_FILTR_PRODUCT, NO_FILTR_PRODUCT_GROUP, GET_CONTRACTOR_IN_API, GET_REPORT_SVERKA, GET_START_DATE_COST, TEST_INLINE_MODE, GET_TANKS, GET_REPORT_ANALYSIS, GET_START_DATE_TRADE_ALKAN, SEND_NAME, CHECK_SAVE_NAME, SUCCESS, SAVE_CONTACT, START, GET_BRANCH, GET_CONTRACTORS, PAGINATION, NEUTRAL, GET_WAREHOUSE, GET_PRODUCTS_IN_API, GET_TYPE_CONTRACTOR, GET_REPORT_DC, GET_REPORT_CASH_BOX, GET_CASH_BOX, GET_REPORT_COST, GET_TYPE_FILE, GET_LANGUAGE;

}
